coverage:
  range: 70..100
  round: down
  precision: 2
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 2%

  ignore:
    - "**/*.test.*"
    - "**/*.spec.*"
    - "**/test/**"
    - "**/tests/**"
    - "**/__tests__/**"
    - "**/e2e/**"
    - "**/dist/**"
    - "**/node_modules/**"
    - "**/*.d.ts"
    - "**/migrations/**"
    - "**/scripts/**"
    - "**/.next/**"
    - "**/coverage/**"
    - "**/docs/**"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
