-- Seed data for Texas native plants (USDA zones 8a-9a)

INSERT INTO plants (
    scientific_name,
    common_names,
    usda_zones,
    water_needs,
    sun_requirements,
    mature_height_ft,
    mature_width_ft,
    growth_rate,
    texas_native,
    drought_tolerant,
    description
) VALUES 
-- Trees
('Quercus virginiana', 
 ARRAY['Live Oak', 'Southern Live Oak'], 
 ARRAY['8a', '8b', '9a', '9b', '10a', '10b'], 
 'Low', 
 'Full Sun to Partial Shade', 
 50, 
 80, 
 'Slow', 
 true, 
 true,
 'Iconic Texas tree with spreading canopy, excellent shade tree'),

('Prosopis glandulosa', 
 ARRAY['Honey Mesquite', 'Texas Mesquite'], 
 ARRAY['7a', '7b', '8a', '8b', '9a', '9b', '10a'], 
 'Very Low', 
 'Full Sun', 
 30, 
 40, 
 'Fast', 
 true, 
 true,
 'Native Texas tree, extremely drought tolerant with filtered shade'),

('Juniperus ashei', 
 ARRAY['Ashe Juniper', 'Mountain Cedar'], 
 ARRAY['7a', '7b', '8a', '8b', '9a'], 
 'Low', 
 'Full Sun to Partial Shade', 
 20, 
 15, 
 'Slow', 
 true, 
 true,
 'Evergreen native to Texas Hill Country, provides year-round color'),

-- Shrubs
('Leucophyllum frutescens', 
 ARRAY['Texas Sage', 'Cenizo', 'Purple Sage'], 
 ARRAY['8a', '8b', '9a', '9b', '10a', '10b'], 
 'Very Low', 
 'Full Sun', 
 8, 
 8, 
 'Moderate', 
 true, 
 true,
 'Popular flowering shrub, blooms after summer rains'),

('Salvia greggii', 
 ARRAY['Autumn Sage', 'Cherry Sage'], 
 ARRAY['7a', '7b', '8a', '8b', '9a', '9b', '10a'], 
 'Low', 
 'Full Sun to Partial Shade', 
 3, 
 3, 
 'Fast', 
 true, 
 true,
 'Long-blooming perennial, attracts hummingbirds and butterflies'),

('Callicarpa americana', 
 ARRAY['American Beautyberry', 'Texas Beautyberry'], 
 ARRAY['7a', '7b', '8a', '8b', '9a', '9b'], 
 'Medium', 
 'Partial Shade to Full Shade', 
 6, 
 6, 
 'Fast', 
 true, 
 false,
 'Deciduous shrub with stunning purple berries in fall'),

-- Grasses
('Muhlenbergia capillaris', 
 ARRAY['Pink Muhly Grass', 'Gulf Muhly'], 
 ARRAY['7a', '7b', '8a', '8b', '9a', '9b', '10a'], 
 'Low', 
 'Full Sun', 
 3, 
 3, 
 'Fast', 
 true, 
 true,
 'Ornamental grass with spectacular pink plumes in fall'),

('Bouteloua gracilis', 
 ARRAY['Blue Grama Grass'], 
 ARRAY['3a', '3b', '4a', '4b', '5a', '5b', '6a', '6b', '7a', '7b', '8a', '8b', '9a'], 
 'Low', 
 'Full Sun', 
 1.5, 
 1.5, 
 'Moderate', 
 true, 
 true,
 'Native turfgrass alternative, requires minimal maintenance'),

('Schizachyrium scoparium', 
 ARRAY['Little Bluestem'], 
 ARRAY['3a', '3b', '4a', '4b', '5a', '5b', '6a', '6b', '7a', '7b', '8a', '8b', '9a'], 
 'Low', 
 'Full Sun', 
 3, 
 2, 
 'Moderate', 
 true, 
 true,
 'Native bunch grass with beautiful fall color'),

-- Groundcovers
('Phyla nodiflora', 
 ARRAY['Texas Frogfruit', 'Turkey Tangle Fogfruit'], 
 ARRAY['8a', '8b', '9a', '9b', '10a', '10b'], 
 'Low', 
 'Full Sun to Partial Shade', 
 0.5, 
 3, 
 'Fast', 
 true, 
 true,
 'Excellent lawn alternative, attracts butterflies'),

-- Perennials
('Gaillardia pulchella', 
 ARRAY['Indian Blanket', 'Firewheel'], 
 ARRAY['2a', '2b', '3a', '3b', '4a', '4b', '5a', '5b', '6a', '6b', '7a', '7b', '8a', '8b', '9a', '9b', '10a', '10b'], 
 'Low', 
 'Full Sun', 
 2, 
 2, 
 'Fast', 
 true, 
 true,
 'State wildflower of Texas, reseeds readily'),

('Rudbeckia maxima', 
 ARRAY['Giant Coneflower'], 
 ARRAY['4a', '4b', '5a', '5b', '6a', '6b', '7a', '7b', '8a', '8b', '9a'], 
 'Medium', 
 'Full Sun to Partial Shade', 
 6, 
 3, 
 'Fast', 
 true, 
 false,
 'Tall perennial with large yellow flowers, attracts pollinators'),

-- Vines
('Lonicera sempervirens', 
 ARRAY['Coral Honeysuckle', 'Trumpet Honeysuckle'], 
 ARRAY['4a', '4b', '5a', '5b', '6a', '6b', '7a', '7b', '8a', '8b', '9a'], 
 'Medium', 
 'Full Sun to Partial Shade', 
 20, 
 6, 
 'Fast', 
 true, 
 false,
 'Native vine with tubular flowers, attracts hummingbirds'),

-- Agaves and Succulents
('Agave americana', 
 ARRAY['Century Plant', 'American Agave'], 
 ARRAY['8a', '8b', '9a', '9b', '10a', '10b'], 
 'Very Low', 
 'Full Sun', 
 6, 
 10, 
 'Slow', 
 true, 
 true,
 'Dramatic architectural plant, blooms once after many years'),

('Opuntia engelmannii', 
 ARRAY['Engelmann''s Prickly Pear', 'Texas Prickly Pear'], 
 ARRAY['8a', '8b', '9a', '9b', '10a', '10b'], 
 'Very Low', 
 'Full Sun', 
 5, 
 8, 
 'Moderate', 
 true, 
 true,
 'Classic Texas cactus with yellow flowers and edible fruit');