name: Staging Deployment

on:
  push:
    branches:
      - staging

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        continue-on-error: true # Don't block staging on test failures

      - name: Build application
        run: npm run build
        
      - name: Deploy to Vercel Staging
        run: |
          echo "Staging deployment triggered by push to staging branch"
          echo "Vercel will automatically deploy this as a preview deployment"